{
 "title": "UI Performance",
 "time": { "from": "2024-07-08T18:17:29.097Z", "to": "2024-07-08T19:34:17.888Z" },
 "templating": {
  "list": [
   {
    "name": "step_name",
    "label": "Step Name",
    "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> distinct(column: \"step\")\r\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Blocking Time (TBT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total-blocking-time\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"first-contentful-paint\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"largest-contentful-paint\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Speed Index (SI)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed-index\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cumulative-layout-shift\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Longest First-Party Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"longest-first-party-request\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Slowest Network Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"slowest-network-request\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Network Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"network-requests\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mainthread Work Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mainthread-work-breakdown\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interactive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"interactive\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interaction To Next Paint (INP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"ui\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"interaction-to-next-paint\")\r\n  |> filter(fn: (r) => r[\"bucket\"] == \"ui\")\r\n  |> filter(fn: (r) => if \"${step_name}\" == \"All\" then true else contains(value: r[\"step\"], set: ${step_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"\"})\r\n  |> group(columns: [\"step\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}