{
 "title": "Influx_V1",
 "time": { "from": "2024-07-23T03:30:58.080Z", "to": "2024-07-23T15:30:58.080Z" },
 "panels": [
  {
   "title": "Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"score\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TBT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"total-blocking-time\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"first-contentful-paint\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"largest-contentful-paint\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"speed-index\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CLS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"cumulative-layout-shift\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest First-Party Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"longest-first-party-request\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slowest Network Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"slowest-network-request\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"network-requests\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mainthread Work Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"mainthread-work-breakdown\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interactive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"interactive\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interaction To Next Paint (INP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"interaction-to-next-paint\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "first-contentful-paint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}